### ISSUE TITLE
Track implement services

### ISSUE THREAD

**Issue by kevin-sakemaer** [rushio-consulting/stashall#12]
- [ ] implement account service (#8)
- [ ] implement authentication service (#9)
- [ ] implement password service (#10)
- [ ] implements tags service (#11)
